/* eslint-disable prettier/prettier */
export default [
  {
    "plantName": "Alpine Bearberry",
    "climateZone": 1,
    "temperatureMinimum": -60,
    "frostFreeDaysMinimum": 120,
    "precipitationMaximumInInches": 197,
    "precipitationMinimumInInches": 12,
    "droughtTolerance": "None",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": true
  },
  {
    "plantName": "Lingonberry",
    "climateZone": 1,
    "temperatureMinimum": -62,
    "frostFreeDaysMinimum": 120,
    "precipitationMaximumInInches": 276,
    "precipitationMinimumInInches": 10,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Squashberry AKA Mooseberry",
    "climateZone": 1,
    "temperatureMinimum": -62,
    "frostFreeDaysMinimum": 120,
    "precipitationMaximumInInches": 180,
    "precipitationMinimumInInches": 8,
    "droughtTolerance": "Low",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Rocky Mountain Goldenrod",
    "climateZone": 1,
    "temperatureMinimum": -62,
    "frostFreeDaysMinimum": 47,
    "precipitationMaximumInInches": 100,
    "precipitationMinimumInInches": 10,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Tealeaf Willow",
    "climateZone": 1,
    "temperatureMinimum": -62,
    "frostFreeDaysMinimum": 47,
    "precipitationMaximumInInches": 120,
    "precipitationMinimumInInches": 4,
    "droughtTolerance": "None",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Arctic Raspberry",
    "climateZone": 1,
    "temperatureMinimum": -62,
    "frostFreeDaysMinimum": 120,
    "precipitationMaximumInInches": 79,
    "precipitationMinimumInInches": 10,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Cup Plant",
    "climateZone": 2,
    "temperatureMinimum": -49,
    "frostFreeDaysMinimum": 128,
    "precipitationMaximumInInches": 51,
    "precipitationMinimumInInches": 16,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": true
  },
  {
    "plantName": "Indian Ricegrass",
    "climateZone": 2,
    "temperatureMinimum": -43,
    "frostFreeDaysMinimum": 90,
    "precipitationMaximumInInches": 16,
    "precipitationMinimumInInches": 6,
    "droughtTolerance": "High",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Rocky Mountain Maple",
    "climateZone": 2,
    "temperatureMinimum": -43,
    "frostFreeDaysMinimum": 180,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 9,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Balsam Fir",
    "climateZone": 2,
    "temperatureMinimum": -43,
    "frostFreeDaysMinimum": 80,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 13,
    "droughtTolerance": "Low",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Tall Oatgrass",
    "climateZone": 3,
    "temperatureMinimum": -38,
    "frostFreeDaysMinimum": 90,
    "precipitationMaximumInInches": 50,
    "precipitationMinimumInInches": 32,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Orchardgrass",
    "climateZone": 3,
    "temperatureMinimum": -33,
    "frostFreeDaysMinimum": 120,
    "precipitationMaximumInInches": 65,
    "precipitationMinimumInInches": 32,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Western Dogwood",
    "climateZone": 3,
    "temperatureMinimum": -35,
    "frostFreeDaysMinimum": 100,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 18,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Autumn Olive",
    "climateZone": 4,
    "temperatureMinimum": -23,
    "frostFreeDaysMinimum": 150,
    "precipitationMaximumInInches": 45,
    "precipitationMinimumInInches": 28,
    "droughtTolerance": "High",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Port Orford Cedar",
    "climateZone": 5,
    "temperatureMinimum": -12,
    "frostFreeDaysMinimum": 173,
    "precipitationMaximumInInches": 110,
    "precipitationMinimumInInches": 49,
    "droughtTolerance": "Low",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Japanese Cedar",
    "climateZone": 6,
    "temperatureMinimum": -8,
    "frostFreeDaysMinimum": 180,
    "precipitationMaximumInInches": 55,
    "precipitationMinimumInInches": 36,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Engelmann's Daisy",
    "climateZone": 6,
    "temperatureMinimum": -3,
    "frostFreeDaysMinimum": 100,
    "precipitationMaximumInInches": 35,
    "precipitationMinimumInInches": 13,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Weeping Lovegrass",
    "climateZone": 6,
    "temperatureMinimum": -8,
    "frostFreeDaysMinimum": 160,
    "precipitationMaximumInInches": 40,
    "precipitationMinimumInInches": 15,
    "droughtTolerance": "High",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Carolina Silverbell",
    "climateZone": 6,
    "temperatureMinimum": -10,
    "frostFreeDaysMinimum": 160,
    "precipitationMaximumInInches": 80,
    "precipitationMinimumInInches": 40,
    "droughtTolerance": "Low",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Northern Spiderlily",
    "climateZone": 6,
    "temperatureMinimum": -3,
    "frostFreeDaysMinimum": 175,
    "precipitationMaximumInInches": 55,
    "precipitationMinimumInInches": 32,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "St. Peterswort",
    "climateZone": 6,
    "temperatureMinimum": -8,
    "frostFreeDaysMinimum": 170,
    "precipitationMaximumInInches": 48,
    "precipitationMinimumInInches": 32,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Eastern Baccharis",
    "climateZone": 6,
    "temperatureMinimum": -3,
    "frostFreeDaysMinimum": 180,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 36,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Mule-Fat",
    "climateZone": 6,
    "temperatureMinimum": -3,
    "frostFreeDaysMinimum": 160,
    "precipitationMaximumInInches": 18,
    "precipitationMinimumInInches": 10,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Nutmeg Hickory",
    "climateZone": 6,
    "temperatureMinimum": -10,
    "frostFreeDaysMinimum": 240,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 40,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Partridge Pea",
    "climateZone": 6,
    "temperatureMinimum": -3,
    "frostFreeDaysMinimum": 130,
    "precipitationMaximumInInches": 45,
    "precipitationMinimumInInches": 14,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Live Oak",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 240,
    "precipitationMaximumInInches": 70,
    "precipitationMinimumInInches": 32,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Valley Oak",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 200,
    "precipitationMaximumInInches": 40,
    "precipitationMinimumInInches": 16,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Southern Magnolia",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 220,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 35,
    "droughtTolerance": "Low",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Fernleaf Biscuitroot",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 240,
    "precipitationMaximumInInches": 100,
    "precipitationMinimumInInches": 14,
    "droughtTolerance": "High",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Shaggy Blazing Star",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 200,
    "precipitationMaximumInInches": 65,
    "precipitationMinimumInInches": 30,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Chaparral Yucca",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 200,
    "precipitationMaximumInInches": 14,
    "precipitationMinimumInInches": 8,
    "droughtTolerance": "High",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "California Poppy",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 120,
    "precipitationMaximumInInches": 18,
    "precipitationMinimumInInches": 8,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Southwestern Pricklypoppy",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 200,
    "precipitationMaximumInInches": 12,
    "precipitationMinimumInInches": 6,
    "droughtTolerance": "High",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Redwood",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 180,
    "precipitationMaximumInInches": 200,
    "precipitationMinimumInInches": 20,
    "droughtTolerance": "Low",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Saw Palmetto",
    "climateZone": 7,
    "temperatureMinimum": 7,
    "frostFreeDaysMinimum": 180,
    "precipitationMaximumInInches": 80,
    "precipitationMinimumInInches": 35,
    "droughtTolerance": "High",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Bayhops",
    "climateZone": 8,
    "temperatureMinimum": 17,
    "frostFreeDaysMinimum": 365,
    "precipitationMaximumInInches": 80,
    "precipitationMinimumInInches": 30,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "Arabian Coffee",
    "climateZone": 8,
    "temperatureMinimum": 17,
    "frostFreeDaysMinimum": 365,
    "precipitationMaximumInInches": 100,
    "precipitationMinimumInInches": 60,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Tolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Seagrape",
    "climateZone": 8,
    "temperatureMinimum": 17,
    "frostFreeDaysMinimum": 365,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 20,
    "droughtTolerance": "High",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": true
  },
  {
    "plantName": "Saguaro",
    "climateZone": 8,
    "temperatureMinimum": 15,
    "frostFreeDaysMinimum": 240,
    "precipitationMaximumInInches": 10,
    "precipitationMinimumInInches": 2,
    "droughtTolerance": "High",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Brown Mustard",
    "climateZone": 8,
    "temperatureMinimum": 17,
    "frostFreeDaysMinimum": 130,
    "precipitationMaximumInInches": 80,
    "precipitationMinimumInInches": 30,
    "droughtTolerance": "Low",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": true
  },
  {
    "plantName": "Turtleweed",
    "climateZone": 8,
    "temperatureMinimum": 17,
    "frostFreeDaysMinimum": 200,
    "precipitationMaximumInInches": 60,
    "precipitationMinimumInInches": 28,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Common Bamboo",
    "climateZone": 8,
    "temperatureMinimum": 17,
    "frostFreeDaysMinimum": 365,
    "precipitationMaximumInInches": 100,
    "precipitationMinimumInInches": 60,
    "droughtTolerance": "Medium",
    "shadeTolerance": "Intolerant",
    "edibleForHumans": false
  },
  {
    "plantName": "Pacific Madrone",
    "climateZone": 8,
    "temperatureMinimum": 13,
    "frostFreeDaysMinimum": 200,
    "precipitationMaximumInInches": 163,
    "precipitationMinimumInInches": 15,
    "droughtTolerance": "High",
    "shadeTolerance": "Intermediate",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },
  {
    "plantName": "",
    "climateZone": ,
    "temperatureMinimum": ,
    "frostFreeDaysMinimum": ,
    "precipitationMaximumInInches": ,
    "precipitationMinimumInInches": ,
    "droughtTolerance": "",
    "shadeTolerance": "",
    "edibleForHumans": false
  },

];

{
  "plantName": "",
  "climateZone": ,
  "temperatureMinimum": ,
  "frostFreeDaysMinimum": ,
  "precipitationMaximumInInches": ,
  "precipitationMinimumInInches": ,
  "droughtTolerance": "",
  "shadeTolerance": "",
  "edibleForHumans": false
},
